### ISSUE TITLE
V8 Iteration Plan

### ISSUE THREAD

**Issue by otomad** [otomad/VegasScripts#62]
以下是即将在 v8 支持的新功能。此处只是给我自己提个醒，因此懒得翻译了。

---

## 优先考虑

- 焕新的界面（WinUI 3）。#38
- 更改为**扩展（Vegas 自定义命令）**，而不再是**脚本**，使用方式将会更自由。
- 原音系战法（Shupelunker 战法）。#44
- Flow（让 Vegas 支持更多运动曲线）。#45
- 对参数部分支持条件匹配事件，包括：
  - 奇偶性或指定倍数的第几个到第几个事件时；
  - 指定当事件的持续时间小于、大于、小于或等于、大于或等于、等于某个时长时。#53
- 手动指定数据抹失扩展包的文件路径，而并非固定在脚本文件的同目录下。#58
- 解决 #51。
- 指定当音高超出算法音域范围后，使用的替代算法。
- 与 Miscz 插件的无缝体验，将会将关键帧参数添加到该插件的 TransformOFX 效果插件中。 https://github.com/zzzzzz9125/Miscz/issues/1
- 合并“快速间隔选择”与“查找轨道素材”工具，同时整合 Vegasaur 扩展中的 Select Events 工具。
- “更改调音算法”工具将支持弹性/古典调音算法与移调效果插件之间的转换。
- “批量生成字幕”工具将整合 Vegasaur 同源工具的更多功能，如：Create counter。
- 新工具，将平移/裁切中的关键帧转换到 Miscz 中的 TransformOFX 插件中。
- “自动轨道布局 - 网格布局”将支持完全自定义行列数目并占据整个屏幕的新布局。即行数将不再根据列数自动改变。
- 新增“首页”，可用于快速切换到音MAD / YTPMV、YTP、原音系战法模式。同时可添加常用工具、转换工具、抹失工具到首页。
- 在开启“五线谱视觉效果”时，允许同时开启“映像节奏视觉效果”。
- 允许在多轨模式为不同轨道使用随机的素材偏移量。
- 允许视频拉伸值同步音频拉伸值。
- 原映像节奏视觉效果“斜向扩缩”更名为“斜下扩缩”，并新增新效果“斜上扩缩”。
- 不再仅允许使用 MIDI 格式来获取音符，将新增 UST / USTX 格式（UTAU / OpenUTAU 项目格式）#37、引用来自其它轨道事件的音符、纯音符（持续时间的四分音符、八分音符等，与 om midi 同名功能类似）。
- 支持指定 MIDI、UST、USTX 格式的文本编码，以防乱码。
- MIDI 裁剪改成筛选/过滤，然后新增选取音域范围、指定倍数（奇偶性）的音符。
- 筛选/过滤只提供小于或小于等于，可只填写一边（左侧0，右侧无穷大），两者填一样表示等于。
- 新增“科学音高记号”新栏目。
- 乐曲新增“文字转语音”（输入文字自动说话）
- 人力Vocaloid / Rap 功能。正准备开发一个视频音源制作器，等到制作器做完之后才能开发本功能。不然连我自己都没法调试。#43 [查看详情 >](#视频音源制作器)
- 新工具，在当前位置创建一个空文本媒体发生器（隔壁om midi同样要新增）。
- 在报错对话框显示当前Vegas版本和Otomad Helper版本。
- 画面的”禁止延长“也更改为下拉框选择，包含以下选项：
  - 可延长
  - 冻结尾帧
  - 截断尾帧
  - 分割后冻结
  - 冻结至黑白
- 原关闭禁止延长时的效果为“可延长”，原开启禁止延长时的效果为“冻结尾帧”
- 如为音频时则仅有“可延长”与“截断尾帧”可用。
- 人力功能允许指定一个音节来代替音源中所有缺失的音节。
- 歌词 / 卡拉OK 字幕功能。#42
- “转换音乐节拍”更改为“耙爪器”，参考自FL Studio的功能。
- “自定渐入增益”新增来自[CustomFades](https://github.com/RatinFX/CustomFades)的功能。

## 积压工作
以下功能在首个版本发布时暂时不考虑新增，等后续版本跟进。

- 写一个新的 MIDI 解析器，辅助现有 MIDI 解析器 NAudio。以便支持某些特殊格式的 MIDI 文件，而不再需要使用 FL Studio 转换 MIDI 格式。同时方便 Reaper 用户更好地支持 MIDI 格式。#39

## 暂不支持
至少短时间内不会有下述功能。

- 编辑 MIDI 文件中各轨道的音符。#40
- 编辑 UST / USTX 文件中的音符和歌词。
- 商城功能。#41

---

# 视频音源制作器

将会开发一个视频音源制作器，预计支持以下功能。

- 允许导入 mp4、mov 等常见视频格式，并且也支持 wav、mp3 等音频格式。
- 输出文件格式为 yaml，以记录各音节在视频中对应的时间码是多少。
  - 文件应声明版本号，防止以后更新遇到棘手的兼容性文件。
  - 编码固定 UTF-8。
  - 允许支持多素材，即一个 yaml 可包含多个视频文件，在每个音节声明中指定来自哪个视频。
  - 允许设置偏移量，类似 LRC 歌词文件的 `[offset:]`，可将视频时间码与声明中的时间码的时间补偿，以防错位问题。
  - 允许插入注释
  - 每个音节可包含多个范围，下游可通过以下顺序来决定选择哪个范围的素材：
    1. 与前一个音节相同的源素材，以保持句子的连贯性。
    2. 与所需音高更接近的素材，从而减小调整音高以减少声音发生扭曲。
    3. 此外随机选择素材。
  - 各音节的范围需包含以下参数：开始时间、结束时间、原始音高、源素材编号。
    可选的参数：视频的偏移时间（用来表示当音画不同步，或者想让画面使用与音频不同的时间范围；需包含以下参数：开始时间、结束时间）。
    同时允许扩展自定义参数以便未来添加其它参数。
  - 每个音节可扩展自定义变体，如原音节为 `a`，可添加特殊语态如喊叫变体 `a_shout`、轻声变体 `a_whisper`。
    也可用于表示素材中的不同人说的话，如“讲（港）”字由刘醒说的 `gang_lx`，由梁非凡说的 `gang_lff`。
    自定义变体亦可多种连用，如 `gang_lx_shout`。
    下游会根据 UST / USTX 中的歌词优先选择指定的变体，如缺少对应变体则会回退到更少变体或者原音节。

使用例：

```yaml
# This is a comment.
sources:
  1: "D:/videos/video1.mp4"
  2: "D:/videos/video2.mp4"
offset: 0:00.000
syllables:
  a:
    - start: 00:00.000
      end: 00:01.000
      pitch: E#5
      source: 1
    - start: 00:01.000
      end: 00:02.000
      pitch: B#4
      source: 1
      videoOffset:
        start: 00:01.500
        end: 00:03.000
  a_whisper:
    - start: 00:02.000
    - end: 00:03.000
    - pitch: C6
    - source: 2
```

其中，路径使用正斜杠而不是反斜杠是因为省去转义双写的麻烦，反正不管是改正斜杠还是转义双写你都得改，都一样。

- 软件界面显示视频和音频**波形**以及**语谱图**。可改变进度条或点击音频波形来更改时间。
- 拖动音频区域以创建一个音节，拖动完成后框选区域左上角的输入框立即聚焦，以填写音节名称。
- 按下 <kbd>Ctrl</kbd> 播放一次当前音节音频，同时按下 <kbd>Ctrl</kbd> + <kbd>Alt</kbd> 以 0.5 倍速播放一次当前音节音频。按空格键播放/暂停音视频，同时音节名称里不允许有空格。
- 自动生成音频的原始音高，且允许手动修正。
- 保存为 yaml 文件格式，下次亦可继续编辑。
- 可为每个音节输出为单个音频文件（wav），以方便其它虚拟歌手软件（如：UTAU、OpenUTAU、袅袅）使用音源。
  - 在设置中可开启是否将输出音频格式修改为 44100Hz、单声道、16Bit，以免其它软件不支持音频格式。
- 可输出和导入 zip 压缩文件格式，其中包含有 yaml 配置，以及各视频素材文件，方便打包和分享。
